### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Ralle001** [sebdehne/DehneEVSE-Firmware#2]
Hey!

Do you think it is possible to add Solar Panel support? 

I was looking to add this: 
https://www.farnell.com/datasheets/2166985.pdf

And it should communicate with the main component with a CAT5E cable. Which is probably not that hard but I would love to know your input on this.

Also does your project maximized at 7.2 kW? Or can I set it to 11 kW?

Thank you for your answer

**Comment by sebdehne** [comment]
Three phase 22kW is supported. Regarding solar support, did you read the Readme?

> This firmware has no charging logic at all and relies 100% on some external software, which needs to decide when to allow charing and at which rate. Keeping all the charging logic remote allowes for much more flexable charging logic

So you can easily integrate with your solar setup as you wish.

**Comment by Ralle001** [comment]
Thank you that was my thinking as well

**Comment by Ralle001** [comment]
One more question. Do you have PINs for a CAT5E on the Arduino Nano or should I go with a bigger one for my project.
